### ISSUE TITLE
Support "Escaping Special Characters" and "Wildcard Searches"

### ISSUE THREAD

**Issue by duylong** [zerowidth/lucene_query_parser#3]
Hi,

The rules do not support the "Escaping Special Characters" and "Wildcard Searches".

Examples:

```
program:postfix\/smtpd
program:postfix*
```

Best Regards

**Comment by pkarman** [comment]
Please try out https://github.com/zerowidth/lucene_query_parser/pull/2 and see if it works for you.

**Comment by duylong** [comment]
My solution : 

```
    rule :term do
      ( (escape_special_words | match["\\w.*-"]).repeat(1) ).as(:term) >> (fuzzy | boost).maybe
    end

    rule :escape_special_words do
      (str('\\') >> match['^\\w']).repeat(1)
    end
```

I prefer this solution in order to avoid to define a regexp to constructor. This is more common in my case.

**Comment by pkarman** [comment]
please review and comment on #9 as it uses this approach plus the term_re feature from #2

**Comment by zerowidth** [comment]
#9 is merged.
